apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-prod-setup-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-prod-setup
  template:
    metadata:
      labels:
        app: k8s-prod-setup
    spec:
      containers:
        - name: k8s-prod-setup
          image: k8s-prod-setup:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: k8s-prod-setup-config
                  key: APP_ENV
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: k8s-prod-setup-config
                  key: APP_NAME
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: k8s-prod-setup-secret
                  key: SECRET_KEY
